### PR TITLE
Pin Codex CLI, fix signing, isolate test gitconfig

### LINKED ISSUE #89: codex-cli driver produces unsigned commits despite global `commit.gpgsign=true`
### Summary

When `git_user.signing_key` is configured, `lib/harness.sh` enables SSH commit signing globally inside the container via `lib/signing.sh` (`gpg.format=ssh`, `user.signingkey=/etc/swarm/signing_key`, `commit.gpgsign=true`). The `claude-code` driver inherits this and produces signed commits. The `codex-cli` driver produces **unsigned** commits, forcing a manual rebase + resign on the host before push.

### Steps to reproduce

Configure a swarm with both `claude-code` and `codex-cli` agent groups and a valid `git_user.signing_key`. After a run:

```
$ git log -1 --pretty=format:"%G? %GK" <claude-commit>
U SHA256:...

$ git log -1 --pretty=format:"%G? %GK" <codex-commit>
N
```

### Expected vs actual behavior

Commits should be signed if signing key is provided.

### Version

`0.20.10`

### PR DESCRIPTION
**Pull request by BowTiedRadone**
## Summary
- Make Codex CLI version configurable per swarm via a `codex_cli_version` swarmfile field, mirroring `claude_code_version`.
- Fix codex agents committing unsigned: copy the bind-mounted signing key to a writable 0600 scratch path so `ssh-keygen -Y sign` accepts it (without this, codex silently retries with `--no-gpg-sign` per [openai/codex#6199](https://github.com/openai/codex/issues/6199)).
- Isolate `test_session_end_push.sh` and `test_launch.sh` from the host gitconfig so SSH-SK / `commit.gpgsign` setups don't trip scratch-repo commits.
## Changes
- `Dockerfile`: add `ARG CODEX_CLI_VERSION=` and templated install: `npm install -g "@openai/codex${CODEX_CLI_VERSION:+@$CODEX_CLI_VERSION}"` (empty arg keeps "latest" behavior).
- `launch.sh`: read `codex_cli_version` via `jq` and forward as `--build-arg` only when set, matching the `_cc_version` pattern.
- `lib/drivers/codex-cli.sh`: update `agent_install_cmd`'s heredoc to the same templated line; comment documents `CODEX_CLI_VERSION`.
- `lib/signing.sh`: `configure_git_signing` now `install -m 0600`'s the source key to `/dev/shm/swarm-signing-key` (tmpfs, RAM-backed, per-container) and points `user.signingkey` at the copy. Optional 2nd arg lets tests override the destination.
- `tests/test_harness.sh`: add 4 assertions: copy exists, perms are 0600, `user.signingkey` points at the copy, and nothing leaks into `$HOME/.ssh/`.
- `tests/test_drivers.sh`: assert the codex install snippet references `CODEX_CLI_VERSION`.
- `tests/test_session_end_push.sh`, `tests/test_launch.sh` — export `GIT_CONFIG_GLOBAL=/dev/null` and `GIT_CONFIG_SYSTEM=/dev/null` so host SSH-SK signing config doesn't prompt for a hardware-key touch on every internal `git commit`.
## Self-review checklist

- [ ] This PR addresses a **single concern** ([why?](https://blog.ploeh.dk/2015/01/15/10-tips-for-better-pull-requests/#2-do-only-one-thing)). If it covers multiple independent changes, I've split them into separate PRs.

## Test plan
- [x] `./tests/test.sh --unit` — expect 11 files, 1186 tests, 0 failed.
- [x] Build with no codex pin: `docker build --build-arg SWARM_AGENTS=codex-cli .` — `codex --version` reports latest published release.
- [x] Build with a pin: add `"codex_cli_version": "0.125.0"` to a swarmfile, run `./launch.sh start`, confirm image's `codex --version` matches.
- [x] Signing e2e: with a 0644 host key bind-mounted at `/etc/swarm/signing_key`, both `codex exec` and `claude -p` commits show `git log --format='%G?'` = `G` and `%GS` = the configured signer.
- [x] `shellcheck -s bash launch.sh lib/drivers/codex-cli.sh lib/signing.sh tests/test_session_end_push.sh tests/test_launch.sh tests/test_drivers.sh tests/test_harness.sh`.

Fixes #89.

### CODE REVIEW

File: tests/test_harness.sh [hunk 1]
```diff
@@ -655,6 +655,33 @@ assert_eq "signing key absent -> gpgsign false" \
...
+# path with 0600 perms and point user.signingkey at the copy,
+# so ssh-keygen does not reject it as "UNPROTECTED PRIVATE KEY
+# FILE".
+copy_sandbox="$TMPDIR/sign-copy-$$-${RANDOM}"
+mkdir -p "$copy_sandbox"
+copy_src="$copy_sandbox/src_key"
+copy_dst="$copy_sandbox/dst_key"
+echo "fake-key-bytes" > "$copy_src"
+chmod 644 "$copy_src"
+HOME="$copy_sandbox" configure_git_signing "$copy_src" "$copy_dst"
```
Comment (moodmosaic) [inline tests/test_harness.sh:670]: That's a host-state side effect from a unit test, plus a potential cross-process race if two `test.sh --unit` runs overlap, plus a likely failure on some OS where /dev/shm doesn't exist as a directory?

Comment (moodmosaic) [reply tests/test_harness.sh:670]: Perhaps thread an explicit sandbox dst_key into the existing helper too, e.g.:
```bash
HOME="$sandbox" configure_git_signing "$key_path" "$sandbox/dst_key"
```

File: lib/signing.sh [hunk 2]
```diff
@@ -1,20 +1,31 @@
...
+# at /etc/swarm/signing_key) and by tests/test_harness.sh with
+# a sandbox path.
 
 configure_git_signing() {
-    local key_path="${1:-/etc/swarm/signing_key}"
-    if [ -f "$key_path" ]; then
+    local src_key="${1:-/etc/swarm/signing_key}"
+    local dst_key="${2:-/dev/shm/swarm-signing-key}"
+    if [ -f "$src_key" ]; then
+        install -m 0600 "$src_key" "$dst_key"
```
Comment (moodmosaic) [inline lib/signing.sh]: If `install -m 0600 fails` (missing /dev/shm, full tmpfs, perms), the function continues to set user.signingkey to a path that doesn't exist. *(?)*

In production this is fine because the harness runs `set -euo pipefail` and the failure aborts startup loudly -- but only because of an external invariant.

Perhaps a defensive `install ... || return 1` (or moving `install` after a guard so a stale signingkey isn't written) would make the function self-contained and more honest in the test harness too.

File: launch.sh [hunk 3]
```diff
@@ -259,11 +259,14 @@ cmd_start() {
 
     local _cc_version
     _cc_version=$(jq -r '.claude_code_version // empty' "$CONFIG_FILE" 2>/dev/null || true)
+    local _codex_cli_version
```
Comment (moodmosaic) [inline launch.sh:262]: `tests/test_launch.sh` §29 pins `jq` parsing of `claude_code_version` (present and absent cases).

This PR adds the parallel `codex_cli_version` plumbing but no §parallel test. I think it's cheap/easy to copy, and prevents a future `jq` filter typo from going unnoticed.

File: lib/signing.sh [hunk 4]
```diff
@@ -1,20 +1,31 @@
...
+# reacts by silently passing --no-gpg-sign on its retry
+# (openai/codex#6199), so commits land without a signature.
 #
-# Sourced by lib/harness.sh inside the container (key at
-# /etc/swarm/signing_key) and by tests/test_harness.sh with a
-# sandbox path.
+# The destination lives outside $HOME on purpose.  $HOME is the
+# agent's namespace, not the harness's.  Default is /dev/shm
+# (tmpfs, RAM-backed, per-container in Docker) so the private
+# key bytes never hit disk; 0600 perms keep it from other users.
```
Comment (moodmosaic) [inline lib/signing.sh]: Strictly speaking `/dev/shm` in Docker is per-container, so "other users" really means "other UIDs in the same container," which is the `agent` user vs. anything else. Wording is fine, just observing.

File: tests/test_drivers.sh [hunk 5]
```diff
@@ -820,6 +820,7 @@ assert_contains "codex jq has changes path" "changes" "$CDX_JQ"
 CDX_INSTALL=$(agent_install_cmd)
 assert_contains "codex install has npm" "npm" "$CDX_INSTALL"
 assert_contains "codex install has @openai/codex" "@openai/codex" "$CDX_INSTALL"
+assert_contains "codex install supports version" "CODEX_CLI_VERSION" "$CDX_INSTALL"
```
Comment (moodmosaic) [inline tests/test_drivers.sh:823]: A behavioral assertion that the empty-arg path produces `@openai/codex` (no `@version`) would catch a future heredoc typo, but it's not load-bearing.

**Review by moodmosaic — COMMENTED** [review]
Thank you for the PR! This is great work, and it looks good and reasonable to merge after addressing the comments, with the potential test leak being the most important one.

I try to review driver PRs as thoroughly as possible because we run swarms overnight, so reliability matters a lot.

Not the case here, but in general, a small driver bug or side effect can derail a full nightly run, waste credits/compute/tokens, or silently produce bad results.

---

In hindsight, bundling provider-specific drivers into the core repo was probably a mistake. The core evolves relatively slowly, while drivers and their underlying CLIs change much faster and break in more surprising ways.

But as long as these drivers live here, they need careful review until we perhaps move them out of core.

HTH 🙏

File: tests/test_harness.sh (hunk 1 above)
Comment (BowTiedRadone) [reply tests/test_harness.sh:670]: [9370640](https://github.com/protocol-security/claude-swarm/pull/91/commits/93706404a1266ed8352749fe980ba5509021a00e)

File: lib/signing.sh (hunk 2 above)
Comment (BowTiedRadone) [reply lib/signing.sh]: [ca9a374](https://github.com/protocol-security/claude-swarm/pull/91/commits/ca9a37444ca3fa006c5f4e1a5038528930f03d19)

File: launch.sh (hunk 3 above)
Comment (BowTiedRadone) [reply launch.sh:262]: [9887ca2](https://github.com/protocol-security/claude-swarm/pull/91/commits/9887ca235001c4c78b14c6eafb5f999a2c72cd77)

File: lib/signing.sh (hunk 4 above)
Comment (BowTiedRadone) [reply lib/signing.sh]: [ff35323](https://github.com/protocol-security/claude-swarm/pull/91/commits/ff3532376928879a303e6019ce1636af422b39f6)

File: tests/test_drivers.sh (hunk 5 above)
Comment (BowTiedRadone) [reply tests/test_drivers.sh:823]: [c0e0405](https://github.com/protocol-security/claude-swarm/pull/91/commits/c0e040572e412158b03c040b86a02e49438730a2)

**Comment by BowTiedRadone** [comment]
@moodmosaic Did you see this failure before? Looks pretty weird: https://github.com/protocol-security/claude-swarm/actions/runs/25044315156/job/73355283090?pr=91

**Comment by BowTiedRadone** [comment]
Update: seems that previously failed test is flaky.

File: tests/test_harness.sh (hunk 1 above)
Comment (moodmosaic) [reply tests/test_harness.sh:670]: Very nice fix!

**Review by moodmosaic — DISMISSED** [review]
LGTM! All comments are addressed.

**Comment by moodmosaic** [comment]
> Update: seems that previously failed test is flaky.

That's possible, yes.

**Review by moodmosaic — APPROVED** [review]

**Comment by moodmosaic** [comment]
> Update: seems that previously failed test is flaky.

Tracked here: https://github.com/protocol-security/claude-swarm/issues/94.
